name: LazleCloud
main: net.lazlecraft.lazlecloud.lazlecloud
version: 1.2
author: LaxWasHere
website: www.LazleCraft.com
commands:
    debug:
        description: test server
    lazlecloud:
        description: tell website
    lazlegames: 
        description: TP hungergames
    survival:
        description: TP survival
    pvp:
        description: TP pvp
    hub:
        description: TP hub
    skyblock:
        description: TP skyblock
    freebuild:
        description: TP Freebuild